version: '3.7'
services:
  web:
    build: .
    env_file:
      - .env
    ports:
      - "5000:5000"
    depends_on:
      - db

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword  # This sets the root password
      MYSQL_DATABASE: flask
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  mysql_data:
